send_command:
  description: Send miio command.
  fields:
    entity_id:
      description: Name of the miio entity.
      example: "light.yeelight_living_e92c"
    method:
      description: Method of the command.
      example: set_power
    params:
      description: Params for the method.
      example: ['on']

set_property:
  description: Set miot property.
  fields:
    entity_id:
      description: Name of the entity.
      example: "light.yeelink_fancl1_45f3"
    field:
      description: Field of property.
      example: power
    value:
      description: Value of property.
      example: True

light_set_scene:
  description: Set a scene.
  fields:
    entity_id:
      description: Name of the light entity.
      example: "light.yeelight_living_e92c"
    scene:
      description: >+
        Number of the scene, between 1 and 8.
        1.早安唤醒
        2.日落助眠
        3.夜灯模式
        4.休闲时光
        5.电影之夜
        6.阅读模式
        7.闪烁提醒
        8.美颜模式
      example: 1
    params:
      description: Params for diy scene.
      example: >
        ['cf',6,0,'600,2,4000,70,400,2,4000,1']

light_set_delayed_turn_off:
  description: Delayed turn off.
  fields:
    entity_id:
      description: Name of the light entity.
      example: "light.yeelight_living_e92c"
    time_period:
      description: Time period for the delayed turn off.
      example: "120, '2:00', {'minutes': 5}"
    power:
      description: Turn on before set delay.
      example: True
